<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <OutputPath>bin\$(Configuration)\$(TargetFramework)\</OutputPath>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>0.0.0.0</AssemblyVersion>
    <Version>0.0.0.0</Version>
    <FileVersion>0.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup>
    <Summary>Plisky.Fallout.Fusion, providing plisky library support to the Fallout build engine.</Summary>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <ReleaseNotesFile>..\_Dependencies\SupportingFiles\release-notes.md</ReleaseNotesFile>
    <PackageId>Plisky.Fallout.Fusion</PackageId>
    <Authors>https://github.com/Itsey</Authors>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://itsey.github.io/</PackageProjectUrl>
    <Description>Plisky.Fallout.Fusion providing plisky tool support to the Fallout build engine..</Description>
    <Copyright>Copyright 2026</Copyright>
    <PackageTags>fallout;cli;build</PackageTags>
    <PackageIcon>pff-icon.png</PackageIcon>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>portable</DebugType>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\_Dependencies\Packaging\pff-icon.png" Pack="true" PackagePath="" />
    <None Include="..\_Dependencies\Packaging\readme.md" Pack="true" PackagePath="" />
  </ItemGroup>
  <Target Name="AddReleaseNotesToPackage" BeforeTargets="GenerateNuspec">
    <Message Importance="high" Text="Creating Custom Release Notes." />
    <PropertyGroup>
      <PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)\..\_Dependencies\Packaging\changelog.md"))</PackageReleaseNotes>
    </PropertyGroup>
  </Target>
  <ItemGroup>
    <PackageReference Include="Fallout.Common" Version="10.4.0" />
    <PackageReference Include="Flurl.Http" Version="4.0.2" />
    <PackageReference Include="NuGet.Packaging" Version="7.9.0" />
</ItemGroup>
</Project>